---
- name: Create Talos OS VM on Proxmox
  hosts: localhost
  gather_facts: no

  vars:
    api_url: "https://192.168.3.10:8006/api2/json"
    api_user: "tint"
    api_password: "12345678"
    node: "pve"
    vm_name: "ControlPlane1"
    vm_id: 130
    vm_os: "l26"  # Giá trị hợp lệ cho Linux
    vm_disk_size: 50
    vm_memory: 8192
    vm_cores: 6
    vm_cpu_type: "x86-64-v2-AES" # Type CPU

  tasks:
    - name: Get Proxmox API ticket
      uri:
        url: "{{ api_url }}/access/ticket"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ api_user }}"
          password: "{{ api_password }}"
          realm: "pve"
        headers:
          Content-Type: application/x-www-form-urlencoded
        validate_certs: no
      register: login_response
      failed_when: login_response.status != 200
      retries: 3
      delay: 5

    - name: Fail if login unsuccessful
      fail:
        msg: "Failed to authenticate with Proxmox API"
      when: login_response.status != 200

    - name: Create VM
      uri:
        url: "{{ api_url }}/nodes/{{ node }}/qemu"
        method: POST
        headers:
          Content-Type: application/json
          Cookie: "PVEAuthCookie={{ login_response.json.data.ticket }}"
          CSRFPreventionToken: "{{ login_response.json.data.CSRFPreventionToken }}"
        body_format: json
        body:
          vmid: "{{ vm_id }}"
          name: "{{ vm_name }}"
          ostype: "{{ vm_os }}"
          ide2: "local:iso/ubuntu-22.04.4-live-server-amd64.iso,media=cdrom"
          cores: "{{ vm_cores }}"
          memory: "{{ vm_memory }}"
          net0: "virtio,bridge=vmbr0"
          onboot: yes
          scsihw: virtio-scsi-pci
          bootdisk: scsi0
          scsi0: "local-lvm:{{ vm_disk_size }}"
          cpu: "{{ vm_cpu_type }}"
        validate_certs: no
      register: create_vm_response

    - name: Fail if creating VM failed
      fail:
        msg: "Failed to create VM"
      when: create_vm_response.status != 200
