- name: Xóa các máy ảo trên Proxmox
  hosts: localhost
  gather_facts: no
  vars:
    api_url: "https://192.168.3.10:8006/api2/json"  # URL API của Proxmox
    api_user: "tint"                               # Tên đăng nhập
    api_password: "12345678"                        # Mật khẩu
    vm_ids_to_delete: "{{ range(105, 109) | list }}" # Danh sách các ID máy ảo cần xóa

  tasks:
    - name: Lấy phiếu API Proxmox
      uri:
        url: "{{ api_url }}/access/ticket"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ api_user }}"
          password: "{{ api_password }}"
          realm: "pve"                              # Đặt realm là Proxmox VE
        headers:
          Content-Type: application/x-www-form-urlencoded
        validate_certs: no
      register: login_response
      failed_when: login_response.status != 200
      retries: 3
      delay: 5

    - name: Báo lỗi nếu đăng nhập không thành công
      fail:
        msg: "Không thể xác thực với API Proxmox"
      when: login_response.status != 200

    - name: Xóa VM
      uri:
        url: "{{ api_url }}/nodes/pve/qemu/{{ item }}"
        method: DELETE
        headers:
          Cookie: "PVEAuthCookie={{ login_response.json.data.ticket }}"
          CSRFPreventionToken: "{{ login_response.json.data.CSRFPreventionToken }}"
        validate_certs: no
      loop: "{{ vm_ids_to_delete }}"
      register: delete_response

    - name: Báo lỗi nếu xóa VM không thành công
      fail:
        msg: "Không thể xóa VM"
      when: delete_response | failed
